// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddhtwkezcxzjfseuelxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkaHR3a2V6Y3h6amZzZXVlbHhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0OTc0MTQsImV4cCI6MjA2MzA3MzQxNH0.YqXIOYaZcP88MOGgMkh6JZXEvJmo8HfeAQhP26ZC42E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);